swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /periodos-rol-usuarios/:
    get:
      tags:
      - periodos-rol-usuarios
      description: get PeriodoRolUsuario
      operationId: PeriodoRolUsuarioController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoRolUsuario'
        "403":
          description: ""
    post:
      tags:
      - periodos-rol-usuarios
      description: create PeriodoRolUsuario
      operationId: PeriodoRolUsuarioController.Post
      parameters:
      - in: body
        name: body
        description: body for PeriodoRolUsuario content
        required: true
        schema:
          $ref: '#/definitions/models.PeriodoRolUsuario'
      responses:
        "201":
          description: '{int} models.PeriodoRolUsuario'
        "403":
          description: body is empty
  /periodos-rol-usuarios/{id}:
    get:
      tags:
      - periodos-rol-usuarios
      description: get PeriodoRolUsuario by id
      operationId: PeriodoRolUsuarioController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoRolUsuario'
        "403":
          description: :id is empty
    put:
      tags:
      - periodos-rol-usuarios
      description: update the PeriodoRolUsuario
      operationId: PeriodoRolUsuarioController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for PeriodoRolUsuario content
        required: true
        schema:
          $ref: '#/definitions/models.PeriodoRolUsuario'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.PeriodoRolUsuario'
        "403":
          description: :id is not int
    delete:
      tags:
      - periodos-rol-usuarios
      description: delete the PeriodoRolUsuario
      operationId: PeriodoRolUsuarioController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /roles/:
    get:
      tags:
      - roles
      description: get Rol
      operationId: RolController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Rol'
        "403":
          description: ""
    post:
      tags:
      - roles
      description: create Rol
      operationId: RolController.Post
      parameters:
      - in: body
        name: body
        description: body for Rol content
        required: true
        schema:
          $ref: '#/definitions/models.Rol'
      responses:
        "201":
          description: '{int} models.Rol'
        "403":
          description: body is empty
  /roles/{id}:
    get:
      tags:
      - roles
      description: get Rol by id
      operationId: RolController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Rol'
        "403":
          description: :id is empty
    put:
      tags:
      - roles
      description: update the Rol
      operationId: RolController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Rol content
        required: true
        schema:
          $ref: '#/definitions/models.Rol'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Rol'
        "403":
          description: :id is not int
    delete:
      tags:
      - roles
      description: delete the Rol
      operationId: RolController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /sistemas-informacion/:
    get:
      tags:
      - sistemas-informacion
      description: get SistemaInformacion
      operationId: SistemaInformacionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SistemaInformacion'
        "403":
          description: ""
    post:
      tags:
      - sistemas-informacion
      description: create SistemaInformacion
      operationId: SistemaInformacionController.Post
      parameters:
      - in: body
        name: body
        description: body for SistemaInformacion content
        required: true
        schema:
          $ref: '#/definitions/models.SistemaInformacion'
      responses:
        "201":
          description: '{int} models.SistemaInformacion'
        "403":
          description: body is empty
  /sistemas-informacion/{id}:
    get:
      tags:
      - sistemas-informacion
      description: get SistemaInformacion by id
      operationId: SistemaInformacionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SistemaInformacion'
        "403":
          description: :id is empty
    put:
      tags:
      - sistemas-informacion
      description: update the SistemaInformacion
      operationId: SistemaInformacionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for SistemaInformacion content
        required: true
        schema:
          $ref: '#/definitions/models.SistemaInformacion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SistemaInformacion'
        "403":
          description: :id is not int
    delete:
      tags:
      - sistemas-informacion
      description: delete the SistemaInformacion
      operationId: SistemaInformacionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /usuarios/:
    get:
      tags:
      - usuarios
      description: get Usuario
      operationId: UsuarioController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Usuario'
        "403":
          description: ""
    post:
      tags:
      - usuarios
      description: create Usuario
      operationId: UsuarioController.Post
      parameters:
      - in: body
        name: body
        description: body for Usuario content
        required: true
        schema:
          $ref: '#/definitions/models.Usuario'
      responses:
        "201":
          description: '{int} models.Usuario'
        "403":
          description: body is empty
  /usuarios/{id}:
    get:
      tags:
      - usuarios
      description: get Usuario by id
      operationId: UsuarioController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Usuario'
        "403":
          description: :id is empty
    put:
      tags:
      - usuarios
      description: update the Usuario
      operationId: UsuarioController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Usuario content
        required: true
        schema:
          $ref: '#/definitions/models.Usuario'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Usuario'
        "403":
          description: :id is not int
    delete:
      tags:
      - usuarios
      description: delete the Usuario
      operationId: UsuarioController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.PeriodoRolUsuario:
    title: PeriodoRolUsuario
    type: object
    properties:
      Activo:
        type: boolean
      FechaCreacion:
        type: string
      FechaFin:
        type: string
      FechaInicio:
        type: string
      FechaModificacion:
        type: string
      Finalizado:
        type: boolean
      Id:
        type: integer
        format: int64
      RolId:
        $ref: '#/definitions/models.Rol'
      UsuarioId:
        $ref: '#/definitions/models.Usuario'
  models.Rol:
    title: Rol
    type: object
    properties:
      Activo:
        type: boolean
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      SistemaInformacionId:
        $ref: '#/definitions/models.SistemaInformacion'
  models.SistemaInformacion:
    title: SistemaInformacion
    type: object
    properties:
      Activo:
        type: boolean
      Descripcion:
        type: string
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.Usuario:
    title: Usuario
    type: object
    properties:
      Activo:
        type: boolean
      Documento:
        type: string
      FechaCreacion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
tags:
- name: sistemas-informacion
  description: |
    SistemaInformacionController operations for SistemaInformacion
- name: roles
  description: |
    RolController operations for Rol
- name: usuarios
  description: |
    UsuarioController operations for Usuario
- name: periodos-rol-usuarios
  description: |
    PeriodoRolUsuarioController operations for PeriodoRolUsuario
